rootProject.name = 'istad-ite-project'
includeBuild 'istad-common'
includeBuild 'microservice'


include 'microservice:customer-service:customer-service-domain'
include 'microservice:customer-service:customer-service-domain:customer-domain-core'
include 'microservice:customer-service:customer-service-domain:customer-application-service'