pluginManagement {
    includeBuild('../../build-logic')

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

include 'business-service-domain:business-domain-core'
include 'business-service-domain:business-application-service'
include 'business-service-restapi'
include 'business-service-persistence'
include 'business-service-message'
include 'business-service-domain'
include 'business-service-main'